### ISSUE TITLE
Weird player behaviour when having internet connection set to 100% loss

### ISSUE THREAD

**Issue by ReMarkus** [allihoopa/Allihoopa-macOS#18]
1. Play a piece in browse
2. Set conditioner to 100% loss
3. Play another piece

Result: Looks like both pieces are playing, but there's no sound. At one occasion I clicked play on a piece, but the piece that I was playing before that was the one that was actually playing (even though it looked like I was playing the piece I clicked on.)

<img width="888" alt="screen shot 2017-10-11 at 10 06 27" src="https://user-images.githubusercontent.com/15105208/31428714-03e145cc-ae6c-11e7-85be-e010a76a64d3.png">

**Comment by Boerworz** [comment]
This was fixed in #22.
