### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by ReMarkus** [allihoopa/Allihoopa-macOS#19]
I was testing resizing in on browse, when suddenly I wasn't able to resize. I clicked on cancel and after a while I got back to the main window. When clicking browse again the browse window seemed to open, but was transparent. I was not able to click anywhere in the SDK-example. Had to stop from Xcode.

<img width="888" alt="screen shot 2017-10-11 at 10 06 27" src="https://user-images.githubusercontent.com/15105208/31429104-63754e92-ae6d-11e7-8b5e-d3badb2f3c95.png">

Attaching log from the whole session:
[SDK-log.txt](https://github.com/allihoopa/Allihoopa-macOS/files/1374739/SDK-log.txt)

**Comment by ReMarkus** [comment]
Managed to make the SDK-example hang. When playing around with the browse window. Got assert:
Assertion failure in -[NSTableView _uncachedRectHeightOfRow:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.83.101/TableView.subproj/NSTableView.m:2140

Attaching log
[SDK-log2.txt](https://github.com/allihoopa/Allihoopa-macOS/files/1374839/SDK-log2.txt)

**Comment by Boerworz** [comment]
This was fixed in #22.
